### PR TITLE
Fix tests failing due to no output

### PR DESCRIPTION
**Pull request by Eder-K**
As mentioned in https://github.com/precice/systemtests/pull/146, a recent change to the precice.xml file (https://github.com/precice/precice/pull/572) caused most tests to crash due to outdated tutorials. After the PRs https://github.com/precice/tutorials/pull/60 and https://github.com/precice/openfoam-adapter/pull/107 have been merged, this PR should handle the remaining precice-config.xml file related issues.

This PR will contain fixes for each of the affected tests.

- [x] su2-ccx: 
    - [x] fails due to `Wrong attribute "distribution-type"`
    - [x] should work after merging https://github.com/precice/tutorials/pull/60.
    - [x] remove output redirect in ccx-container (https://github.com/precice/systemtests/pull/152#discussion_r365572195)
- [x] of-of: 
    - [x] `distribution-type` as well. Also depends on a line in the .xml file that probably must be adressed
    - [x] need merge of https://github.com/precice/openfoam-adapter/pull/107
- [x] of-of np: 
    - [x] `distribution-type` and additional line dependence, 
    - [x] need merge of https://github.com/precice/openfoam-adapter/pull/107
- [x] of-ccx: 
    - [x] `distribution-type` and additional line dependence.
- [x] fe-fe: 
    - [x] `distribution-type` see https://github.com/precice/systemtests/commit
    - [x] error in deployment phase currently.
    - [x] should work after merging https://github.com/precice/tutorials/pull/60./8d3fe2ed986c21919e787badcd7194fe3f288ec2
- [x] bindings/solverdummies:
    - [x] Currently still [fails](https://travis-ci.org/precice/systemtests/jobs/634663516#L676) due to `distribution-type`.
    - [x] error in deployment phase currently.
    - [x] Should work after merging https://github.com/precice/precice/pull/606. 
- [x] dealii-of:
    - [x] `distribution-type` and additional line dependence.
- [x] nutils-of:
    - [x] `distribution-type` and additional line dependence. (see #149 )
    - [x] error in deployment phase currently.
    - [ ] Hangs if the OF participant starts before the nutils one does.
- [x] [petsc] of-ccx: 
    - [x] fails as a consequence of [PETSc preCICE failing](https://travis-ci.org/precice/systemtests/jobs/638788539).

### CODE REVIEW

**Comment by BenjaminRodenberg** [comment]
I would suggest to merge #146 into this PR. Then we address the problem in a single PR, which is a better approach from my point of view.

**Comment by BenjaminRodenberg** [comment]
> I would suggest to merge #146 into this PR. Then we address the problem in a single PR, which is a better approach from my point of view.

Better idea: Since the (relevant) changes introduced in #146 are a one-liner, it is probably more appropriate to just manually apply these changes here, as well. I will take care of this and close #146.

**Comment by BenjaminRodenberg** [comment]
I created a branch [`systemtests/hardcoded-fix-nooutput`](https://github.com/precice/systemtests/tree/hardcoded-fix-nooutput) that we can use for testing against the tutorials on [`uekerman/tutorials/simplify-parallel-config`](https://github.com/uekerman/tutorials/tree/simplify-parallel-config) until https://github.com/precice/tutorials/pull/60 is merged. 

**Important:** Don't merge [`systemtests/hardcoded-fix-nooutput`](https://github.com/precice/systemtests/tree/hardcoded-fix-nooutput) into this branch or into `develop`. It is only intended for testing purposes! We do not want to have the hardcoded branches in our final implementation

You can manually trigger a build of this branch on travis to test your implementation. I already triggered [a build](https://travis-ci.org/precice/systemtests/builds/635175668). I assume that the FEniCS-FEniCS test should work for that build, since it refers to the correct version of the tutorials.

**Comment by BenjaminRodenberg** [comment]
The tests that I have updated, so far, still have problems with deployment. But I would suggest to first update all the tests such that they run through successfully and then worry about the deployment stage.

**Comment by BenjaminRodenberg** [comment]
I checked [bindings/solverdummies](https://travis-ci.org/precice/systemtests/jobs/635278466) and they seem to work now (ignoring the usual deployment problem), since https://github.com/precice/precice/pull/606 has been merged.

**Comment by BenjaminRodenberg** [comment]
Note that https://github.com/precice/openfoam-adapter/pull/107 is also relevant (for `of-of` and `of-of_np`)

**Comment by Eder-K** [comment]
See https://github.com/precice/systemtests/pull/152#discussion_r365572195

For the SU2-Calculix test, I had to manually disable output in the ccx container so that the Travis log does not reach the size limit (which causes a job error):
https://github.com/precice/systemtests/blob/c2339986665561cd05dbe9845f54898caa0855cc/tests/TestCompose_su2-ccx/docker-compose.yml#L15

Before merging this PR, we should revert this change. it is only needed since we currently have each test output all of its container logs.

**Comment by Eder-K** [comment]
> The tests that I have updated, so far, still have problems with deployment. But I would suggest to first update all the tests such that they run through successfully and then worry about the deployment stage.

The deployment error we see here is noted in https://github.com/precice/systemtests/issues/115 and relates to the commit message that is visible on the Travis job page (the text beside the branch name/PR number), it occurs whenever a build is manually triggered (on the webpage) or triggered by another repository. 
I think we don't need to worry about it, Travis actually does not support the mechanic that would be necessary for it to function (that is to have Travis read commit messages manipulated via API request or manual trigger). Besides, we will hopefully change to the new pushing system in https://github.com/precice/systemtests/pull/147 soon.

**Comment by Eder-K** [comment]
The PETSc of-ccx test depends on the PETSc preCICE image, which is currently failing. This test will only work after https://github.com/precice/systemtests/issues/139 has been resolved.

**Comment by BenjaminRodenberg** [comment]
> 
> 
> The PETSc of-ccx test depends on the PETSc preCICE image, which is currently failing. This test will only work after #139 has been resolved.

In this case I would suggest to allow failure on this test (within the scope of this PR) and fix it at a later point in time.

Then the last test we have to worry about it the nutil-of test. Correct?

**Comment by MakisH** [comment]
@Eder-K I just now discussed with @BenjaminRueth and had a brief look over the nutils case.

A particularity of [this tutorial](https://github.com/precice/tutorials/tree/develop/CHT/flow-over-plate/buoyantPimpleFoam-nutils) is that it is supposed to start the solvers from inside the solvers' directories and `exchange-directory` is set to `..`.

Looking at the [compose file](https://github.com/precice/systemtests/blob/EderK-fix-nooutput/tests/TestCompose_nutils-of.Ubuntu1804/docker-compose.yml#L37-L39), we are wondering about the following:
- Why start the solvers from the home directory? Then we probably don't have access to `..` . @uekerman 
- Why setting a link? `ln -sf /home/precice/Data/Input/* .`
- Why did [this PR](https://github.com/precice/systemtests/pull/132) succeed? What changed in the meantime?

**Comment by BenjaminRodenberg** [comment]
We want to merge this PR until Monday morning. See https://github.com/precice/precice/pull/614#issuecomment-577116110. If it is not 100% ready, we can fix the few failing tests later with a patch.

**Comment by Eder-K** [comment]
The nutils-of test does occasionally work, but specifically when the openfoam participant is launching after the nutils one. I am still trying to find out why this happens, but as a **temporary** workaround setting a manual delay in the openfoam container does resolve the problem.

I am merging this 'hacky' version for now so that the develop branch finally runs the tests again. Meanwhile I will continue working on an actual for the nutils-of test here.

**Comment by MakisH** [comment]
> I am merging this 'hacky' version for now so that the develop branch finally runs the tests again. Meanwhile I will continue working on an actual for the nutils-of test here.

Could you please document this in another issue then?

**Pull request merged**
