### PR TITLE
Change namings to new dealii solver namings

### PR DESCRIPTION
**Pull request by davidscn**
For consistency, we needed to change the naming again according to the new dealii solver (https://github.com/precice/dealii-adapter/pull/25). We have now a test for the linear solver. 

The new dealii adapter has now two coupled solvers. We should add a test for the nonlinear solver as well in a future PR.

We changed `coupled_elasto_dynamics` -> `linear_elasticity`

### CODE REVIEW

**Comment by davidscn** [comment]
@Eder-K Which tutorials are currently tested? The current tutorials will fail additionally, because the individual output has changed.

**Review by Eder-K — APPROVED** [review]

**Comment by davidscn** [comment]
The parameter file name changed as well, I added it. 
Still, the reference data for the tutorial needs to be refreshed.

**Comment by Eder-K** [comment]
Currently, the only deal.ii related test we are running is FSI/flap_perp/OpenFOAM-deal.II.

**Comment by davidscn** [comment]
Ok, can we test the 2D version instead? Should I provide reference data? Or do you want to open up a separate PR on this after the tutorials are merged?

**Comment by davidscn** [comment]
@Eder-K We decided to switch to deal.II minimum version of 9.2.
Can we update the test?

**Comment by Eder-K** [comment]
> Ok, can we test the 2D version instead? Should I provide reference data? Or do you want to open up a separate PR on this after the tutorials are merged?

It might be cleaner to add the other test in a separate PR, so I opened https://github.com/precice/systemtests/pull/232. If you already have existing reference data that would be great, though we might have to adjust it a little.

**Comment by davidscn** [comment]
> If you already have existing reference data that would be great, though we might have to adjust it a little.

Ok, I will push to the other PR as soon as I have them. Do you want the `cout` or `vtk` results?

This PR can be merged as soon as the deal.II version is updated.

**Comment by Eder-K** [comment]
VTK results would be best I think.

**Comment by davidscn** [comment]
Ok, since the version has been updated and the tutorial test has a separate PR, this can be merged.

**Pull request merged**
