### PR TITLE
Allow adapter to trigger custom systemtests build 

### PR DESCRIPTION
**Pull request by shkodm**
**NOTICE**: This should be merged (hopefully) only after #21.  Also one should probably read that PR, before reading this. 

## Problem

 Even when having daily cron-job based builds with Travis several problems might occur. What if in one day several commits were pushed to adapters ( or maybe also preCICE itself ). I know, I know, some adapters are not in active development, but from what I can see some are (e.g.  [openfoam-adapter](https://github.com/precice/openfoam-adapter) ). Then daily build fails, wrong results or failure during building is produced and one has to manually dig through the series of changes in the adapter to find out which one exactly caused the problem. This is not nice. 

Reasoning above should suggest, that some kind of more continuous integration should exist for adapters also ( at least for the master branch ). But we already have the tests for adapters in this repository, that are integrated nicely with Travis ( after #21 ). Can we somehow reuse this functionality for adapters? Of course, we don't want to run full systemtests suite, with all the adapters and additional building of preCICE, but lets say we just use already pushed to dockerhub preCICE image (so that tests will be executed fast enough) and only tests that are related to the adapter are run (e.g. for OpenFOAM we test OpenFOAM-OpenFOAM and OpenFOAM-Calculix, but for SU2 just SU2-Calculix ). How to achieve it with least effort, no code duplication and make sure it is robust and useful? 

## Solution 

Turns out we can use [Travis API v3]( https://docs.travis-ci.com/user/triggering-builds/) to make dependent builds, i.e. we can trigger `systemtests` Travis build during execution of Travis build of e.g. openFOAM adapter. This way we can make integration *continuous*, so new commits on adapters are checked. Now, to make sure, with this customly triggered builds, that only set of tests related to adapter is executed and we do not do any extra work, we can use more features of Travis API, namely use custom job bodies ( and send them via API request as JSON). However, this is not enough, since the maintainers of the adapter ( and the 'passing' or 'fail' badge in the `README.md`...) need to be informed, and we want to keep history of failures of the adapters in its own Travis page. To do this we can again use dependent builds, now making systemtests build trigger custom build of the adapter, that just fails, if the systemtests failed. This way adapter gets to know that it failed, and if desired can find reference output in the [precice_st_output](https://github.com/precice/precice_st_output)

Since build configuration of this custom Travis jobs are pretty similar, with only difference being names of tests to run, names of repositories, etc., we can write general python script that can send triggering of different systemtests (and corresponding failure callback) from different adapter and allows easy addition of new ones. 

Then the only thing remaining is to add `.travis.yml`  to the adapter, which (excluding system specs can be very simple) 
```yml
    - if: branch = master
      script: |
        curl -LO --retry 3 https://raw.githubusercontent.com/precice/systemtests/master/trigger_systemtests.py
        python trigger_systemtests.py --adapter openfoam
``` 
And of course, we need to add `TRAVIS_ACCESS_TOKEN` in each adapter repository as a secure variable, to be used as authentication when triggering Travis with API. But this is not a big price to pay. 

To illustrate, the solution above, following will be executed on commit to OpenFOAM adapter master branch: 

1) Travis starts building openFOAM adapter, send trigger request to systemtests and exits with success 
image
                                                               *openfoam-adapter travis page*

2) Travis starts building systemtests using custom job recipe, that was just sent, runs OpenFOAM-OpenFOAM, OpenFOAM-CalculiX, if everything is fine exits with success, otherwise pushes wrong output and logfile to the output repository and triggers custom Travis build of OpenFOAM
image
                                                 *systemtests travis page (note that only openfoam related tests  are run)* 

3) (If systemtests failed) Travis starts building OpenFOAM, and since the request was just to fail, it fails. Fin. 
image
                                                             *openfoam-adapter travis page*

In this PR I add `trigger_systemtests.py`, that does all of the above. I already tested it on my fork of the Calculix, OpenFOAM, and SU2 adapters. Discussion and suggestions what else can be improved are welcome.

### CODE REVIEW

**Review by MakisH — CHANGES_REQUESTED** [review]
Two notes:
* If I understand correctly, this would lead to an "always success", potentially followed by a failure after a while. So, we should keep in mind that the "success marks" on the adapters may be temporarily false. Could we somehow improve this?
* Add a note on README for the additional steps required by this PR when adding a new system test (i.e. how to map tests to adapters).

**Comment by shkodm** [comment]
@MakisH , 
> If I understand correctly, this would lead to an "always success", potentially followed by a failure after a while. So, we should keep in mind that the "success marks" on the adapters may be temporarily false. Could we somehow improve this? 

So now that I am thinking about it, there can be another approach. We can 
* Start a travis job from the adapter, trigger systemtests, but do not exit immediately, but enter some kind of a while loop like 
```python
while systemTestStatus == "running":
      systemTestStatus = querySystemtests()
return systemTestStatus 
```
This way the job on the adapter will exit only after the job on systemtests finished. This way we will probably have cleaner Travis history, but also first job would be just wasting computing time. I can implement it anyway, just to see how it would work and explore the options.

**Comment by MakisH** [comment]
Can we maybe exit the first run with something else rather than "success" or "failure"? E.g. "interrupted"?

**Comment by shkodm** [comment]
As discussed with @MakisH in person, we decided to add both options. Then each adapter can choose what is most suitable.  Thus I implemented, what I described two comments above and it can be switched on with `--wait` argument. Thus to use it in the adapter:
```yaml
   if: branch = master
      script: 
        - curl -LO --retry 3 https://raw.githubusercontent.com/precice/systemtests/master/trigger_systemtests.py
        - travis_wait 60 python trigger_systemtests.py --adapter openfoam --wait
```
`travis_wait` is used so Travis will not kill our job because of no output. I tested on my adapter forks and everything seems to be working as intended.

**Comment by MakisH** [comment]
Please also have https://github.com/precice/systemtests/issues/25 in mind. But feel free to deal with the Ubuntu-specific issue alltogether in a separate Pull Request.

**Pull request merged**
