### PR TITLE
Update deal.II OpenFOAM reference data

### PR DESCRIPTION
**Pull request by davidscn**
I hope the tests run now on this PR.

### CODE REVIEW

**Comment by davidscn** [comment]
@MakisH I will not update the 18.04 test case, since I have currently no image installed.

**Comment by MakisH** [comment]
> @MakisH I will not update the 18.04 test case, since I have currently no image installed.

Then we should just keep this case as "allowed to fail" for now: https://github.com/precice/systemtests/blob/master/.travis.yml#L12-L19

I also don't have any 18.04 image ready, I would need to set it up.

**Comment by davidscn** [comment]
I cannot see the current status (cancelled) of my updated test. How can I trigger the test (manually)?

**Comment by MakisH** [comment]
You can either commit something, or start it from Travis: https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit (I hope you have permission, if not, let me know)

Currently, the adapters' Travis trigger the systemtests Travis, so it could be a bit more complicated than that.

**Comment by davidscn** [comment]
_mhm_ I committed (obviously in this PR), but for me it looks as follows:
Screenshot from 2021-03-19 10-57-19

**Comment by davidscn** [comment]
This is outdated.

**Pull request closed without merging**
