### PR TITLE
Apply tests to python bindings in precice/python-bindings

### PR DESCRIPTION
**Pull request by BenjaminRodenberg**

### CODE REVIEW

**Comment by BenjaminRodenberg** [comment]
The python bindings from the repository are used by the tests now. The bindings test exits successfully (https://travis-ci.org/precice/systemtests/jobs/620625736?utm_medium=notification&utm_source=github_status). 

However, the fenics-fenics tests seems to make trouble (https://travis-ci.org/precice/systemtests/jobs/620625735?utm_medium=notification&utm_source=github_status). If I try to reproduce the problem locally (since the log of the test being run in Travis does not really help a lot) I get the following output:

```
benjamin@benjamin-ThinkPad-X1-Yoga-2nd:~/systemtests/tests/TestCompose_fe-fe.Ubuntu1804.home$ docker-compose up
Starting tutorial-data ... done
Recreating fenics-adapter-dirichlet ... done
Starting fenics-adapter-neumann     ... done
Attaching to tutorial-data, fenics-adapter-neumann, fenics-adapter-dirichlet
fenics-adapter-neumann      | (0) 13:37:24 [impl::SolverInterfaceImpl]:101 in configure: This is preCICE version 1.5.1
fenics-adapter-neumann      | (0) 13:37:24 [impl::SolverInterfaceImpl]:102 in configure: Configuring preCICE with configuration: "/home/precice/Data/Input/precice-config.xml"
fenics-adapter-neumann      | (0) 13:37:24 [impl::SolverInterfaceImpl]:145 in configure: Run in coupling mode
fenics-adapter-neumann      | (0) 13:37:24 [impl::SolverInterfaceImpl]:214 in initialize: Setting up master communication to coupling partner/s
tutorial-data exited with code 0
fenics-adapter-dirichlet    | Default domain partitioning for simple interface is used: Left part of domain is a Dirichlet-type problem; right part is a Neumann-type problem
fenics-adapter-dirichlet    | Calling FFC just-in-time (JIT) compiler, this may take some time.
fenics-adapter-dirichlet    | Calling FFC just-in-time (JIT) compiler, this may take some time.
fenics-adapter-dirichlet    | Calling FFC just-in-time (JIT) compiler, this may take some time.
fenics-adapter-dirichlet    | (0) 13:37:31 [impl::SolverInterfaceImpl]:101 in configure: This is preCICE version 1.5.1
fenics-adapter-dirichlet    | (0) 13:37:31 [impl::SolverInterfaceImpl]:102 in configure: Configuring preCICE with configuration: "/home/precice/Data/Input/precice-config.xml"
fenics-adapter-dirichlet    | (0) 13:37:31 [impl::SolverInterfaceImpl]:145 in configure: Run in coupling mode
fenics-adapter-dirichlet    | (0) 13:37:31 [impl::SolverInterfaceImpl]:214 in initialize: Setting up master communication to coupling partner/s
fenics-adapter-dirichlet    | (0) 13:37:31 [impl::SolverInterfaceImpl]:219 in initialize: Masters are connected
fenics-adapter-dirichlet    | (0) 13:37:31 [partition::ReceivedPartition]:35 in communicate: Receive global mesh NeumannNodes
fenics-adapter-neumann      | (0) 13:37:31 [impl::SolverInterfaceImpl]:219 in initialize: Masters are connected
fenics-adapter-neumann      | (0) 13:37:31 [partition::ProvidedPartition]:36 in communicate: Gather mesh NeumannNodes
fenics-adapter-neumann      | (0) 13:37:31 [partition::ProvidedPartition]:62 in communicate: Send global mesh NeumannNodes
fenics-adapter-neumann      | (0) 13:37:31 [partition::ProvidedPartition]:79 in compute: Compute partition for mesh NeumannNodes
fenics-adapter-neumann      | (0) 13:37:31 [impl::SolverInterfaceImpl]:223 in initialize: Setting up slaves communication to coupling partner/s
fenics-adapter-neumann      | (0) 13:37:31 [impl::SolverInterfaceImpl]:228 in initialize: Slaves are connected
fenics-adapter-neumann      | (0) 13:37:31 [io::TXTTableWriter]:18 in TXTTableWriter: ERROR: Could not open file "precice-HeatNeumann-iterations.log" for writing txt table data!
fenics-adapter-neumann      | Run finished at Thu Dec  5 13:37:31 2019

```

Can anybody help me understanding this?

**Comment by MakisH** [comment]
I understand that preCICE cannot open (create) the log file to write the implicit coupling iterations numbers:

https://github.com/precice/precice/blob/7e40c1d362ac867f4a0f8c76702cb17ba6febe29/src/io/TXTTableWriter.cpp#L9-L23

I cannot think of any good reason why this happens. Since the participants find each other, this means that preCICE can write & read files in that directory.

Does the file `precice-HeatNeumann-iterations.log` exist already from a previous run (and potentially owned by another user)?

**Comment by BenjaminRodenberg** [comment]
> I understand that preCICE cannot open (create) the log file to write the implicit coupling iterations numbers:
> 
> https://github.com/precice/precice/blob/7e40c1d362ac867f4a0f8c76702cb17ba6febe29/src/io/TXTTableWriter.cpp#L9-L23
> 
> I cannot think of any good reason why this happens. Since the participants find each other, this means that preCICE can write & read files in that directory.
> 
> Does the file `precice-HeatNeumann-iterations.log` exist already from a previous run (and potentially owned by another user)?

Thanks for the hint! I think this is somehow related to the fact that the user `precice` is trying to run the test from `\`. This leads to permission problems. I have no idea why this did not lead to problems before... related: #135

**Comment by MakisH** [comment]
Usually a normal user does not have write access to `/`. Try executing on `/home/precice/` (or actually, you are doing it now already).

Note that the multiple users situation could also lead to problems with OpenFOAM, as e.g. the adapter will be built in the `$FOAM_USER_LIBBIN` directory, which depends on `$HOME`, which depends on the user.

**Pull request merged**
