### PR TITLE
add tests for Ubuntu 19.04

### PR DESCRIPTION
**Pull request by BenjaminRodenberg**
One of the biggest advantages of Ubuntu 19.04 is that we can use pip provided via `apt`. pip of Ubuntu 18.04 or older is not working with the python bindings. See [here](https://github.com/precice/systemtests/pull/96#issuecomment-532640406). Therefore, we should also consider testing Ubuntu 19.04.

# ToDo

- [ ] This PR should only be merged after #123 has been merged.
- [ ] Fix tests. See [here](https://github.com/precice/systemtests/pull/97#issuecomment-532661075)

### CODE REVIEW

**Comment by BenjaminRodenberg** [comment]
In the current version, [I commented out the tests](https://github.com/precice/systemtests/blob/28722fe1370592984d1245b15d7113dadf5d1397/precice/Dockerfile.Ubuntu1904.sudo#L56), since I got an mpi error otherwise:

```
Step 15/20 : RUN cd /home/precice/precice-build && make test_base  # Tests do not work due to error: See ...
 ---> Running in bdeaeae26f0a
-- Found Git: /usr/bin/git (found version "2.20.1") 
-- Revision status: v1.6.1-55-ge802b75b
[  0%] Built target GitRevision
[ 63%] Built target precice
[100%] Built target testprecice
Scanning dependencies of target test_base
UpdateCTestConfiguration  from :/home/precice/precice-build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/precice/precice-build/DartConfiguration.tcl
Test project /home/precice/precice-build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: precice.Base

1: Test command: /usr/bin/mpiexec "-n" "4" "/home/precice/precice-build/testprecice" "--run_test=!@MPI_Ports:!MappingTests/PetRadialBasisFunctionMapping/Parallel/*"
1: Environment variables: 
1:  PRECICE_ROOT=/home/precice/precice
1: Test timeout computed to be: 180
1: --------------------------------------------------------------------------
1: There are not enough slots available in the system to satisfy the 4 slots
1: that were requested by the application:
1:   /home/precice/precice-build/testprecice
1: 
1: Either request fewer slots for your application, or make more slots available
1: for use.
1: --------------------------------------------------------------------------
1/1 Test #1: precice.Base .....................***Failed    0.03 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.03 sec

The following tests FAILED:
	  1 - precice.Base (Failed)
Errors while running CTest
make[3]: *** [CMakeFiles/test_base.dir/build.make:57: CMakeFiles/test_base] Error 8
make[2]: *** [CMakeFiles/Makefile2:248: CMakeFiles/test_base.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:255: CMakeFiles/test_base.dir/rule] Error 2
make: *** [Makefile:262: test_base] Error 2
```

**Comment by MakisH** [comment]
Keep in mind that 19.04 reaches its end-of-life in January 2020. I would suggest that you directly use Ubuntu 19.10 (which also "expires" in July 2020). Ubuntu 20.04 LTS is expected to be released on late April.

**Comment by BenjaminRodenberg** [comment]
> 
> 
> Keep in mind that 19.04 reaches its end-of-life in January 2020. I would suggest that you directly use Ubuntu 19.10 (which also "expires" in July 2020). Ubuntu 20.04 LTS is expected to be released on late April.

Using Ubuntu 19.04 is clearly a workaround until the next LTS is released. The nice thing about Ubuntu 19.04 is that we can install `pip3` via `apt install python3-pip` and get a compatible version (`pip3 --version` is `18.01`). Like explained in https://github.com/precice/systemtests/pull/96#issuecomment-532640406 `pip3` from `apt install python3-pip` is not sufficient (`pip3 --version` is `9.0.1`).

Adding a test makes sure that the `pip3` provided via `apt` will be sufficient in the future or we at least get a failure, if we unintentionally break compatibility again.

**Comment by MakisH** [comment]
> > Keep in mind that 19.04 reaches its end-of-life in January 2020. I would suggest that you directly use Ubuntu 19.10 (which also "expires" in July 2020). Ubuntu 20.04 LTS is expected to be released on late April.
> 
> Using Ubuntu 19.04 is clearly a workaround until the next LTS is released.

Then this test will just break between January and end of April, as Ubuntu 19.04 will not be able to download packages.

**Comment by BenjaminRodenberg** [comment]
> 
> 
> > > Keep in mind that 19.04 reaches its end-of-life in January 2020. I would suggest that you directly use Ubuntu 19.10 (which also "expires" in July 2020). Ubuntu 20.04 LTS is expected to be released on late April.
> > 
> > 
> > Using Ubuntu 19.04 is clearly a workaround until the next LTS is released.
> 
> Then this test will just break between January and end of April, as Ubuntu 19.04 will not be able to download packages.

Then should we use Ubuntu 19.10 instead and as soon as Ubuntu 20.04 is there, upgrade the test? I really would like to have at least one test, where `pip` is installed via `apt`.

**Comment by MakisH** [comment]
> Then should we use Ubuntu 19.10 instead and as soon as Ubuntu 20.04 is there, upgrade the test? I really would like to have at least one test, where `pip` is installed via `apt`.

Yes.

**Comment by fsimonis** [comment]
Can't you simply upgrade pip as a user?
```
pip3 install --user --upgrade pip
```

**Comment by MakisH** [comment]
@BenjaminRueth Shouldn't we close this as deprecated? In any case, upgrading pip as a user is our recommended practice.

**Pull request closed without merging**
