### PR TITLE
Run solverdummies on systemtests

### LINKED ISSUE #12: Test all existing solverdummies
preCICE provides solverdummies for the different bindings in https://github.com/precice/precice/tree/develop/tools/solverdummies. We should test all bindings by running all available solverdummies inside the system tests.

Currently, we only run the python solverdummies in https://github.com/precice/systemtests/blob/PythonBindings/Test_bindings/Dockerfile#L30.

### PR DESCRIPTION
**Pull request by BenjaminRodenberg**
Adds tests for solverdummies in C, CPP, Python, Fortran and f2003

closes #12

### CODE REVIEW

**Review by shkodm — APPROVED** [review]

**Comment by BenjaminRodenberg** [comment]
@shkodm something is still failing. Do you have an idea? A problem with running the test using `python system_testing.py -s bindings`. This problem is not related to the actual test.

**Comment by BenjaminRodenberg** [comment]
It would also be helpful, if we could see the output of the subprocess that is failing in Travis (if it fails). Currently, I only get the [following lines](https://travis-ci.org/precice/systemtests/jobs/545449774#L460-L461):

```
subprocess.CalledProcessError: Command 'docker build --file Dockerfile --tag st_bindings-ubuntu1604.home-develop --build-arg from=[secure]/[secure]-ubuntu1604.home-develop:latest .' returned non-zero exit status 1
The command "python system_testing.py -s bindings" exited with 1.
```

It would be good to know, why `docker build` fails.

**Comment by BenjaminRodenberg** [comment]
[Here](https://travis-ci.org/precice/systemtests/jobs/513621827) it seems to work.

**Comment by shkodm** [comment]
It was just a typo in the dockerile. Everything [works](https://travis-ci.org/precice/systemtests/jobs/545917427) now

**Pull request merged**
